import AppKit
import CryptoKit

/// Watches the system clipboard and records each new copy in the store.
/// macOS has no "clipboard changed" notification, so this checks the change count a few times a second.
@MainActor
final class ClipboardWatcher {
    private let store: HistoryStore
    private var lastChange = NSPasteboard.general.changeCount
    private var timer: Timer?

    /// Markers apps put on copies that shouldn't be kept: passwords, one-time codes, temporary data.
    /// See nspasteboard.org; the 1Password and Bitwarden types cover older versions that skip the standard ones.
    private static let skipTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
        .init("com.bitwarden.desktop"),
    ]

    init(store: HistoryStore) {
        self.store = store
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.check() }
        }
    }

    /// Call after Cubby writes to the clipboard itself, so its own write isn't recorded as a new copy.
    func skipCurrentContents() {
        lastChange = NSPasteboard.general.changeCount
    }

    private func check() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount

        let types = Set(pb.types ?? [])
        guard types.isDisjoint(with: Self.skipTypes) else { return }

        let source = NSWorkspace.shared.frontmostApplication
        let sourceID = source?.bundleIdentifier
        let sourceName = source?.localizedName

        // Files first: Finder also puts the file name on the clipboard as text.
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            let paths = urls.map(\.path).joined(separator: "\n")
            store.add(kind: .file, text: paths, rtf: nil, imageFile: nil,
                      sourceBundleID: sourceID, sourceName: sourceName, hash: Self.hash(Data(paths.utf8)))
            return
        }

        let string = pb.string(forType: .string)
        let trimmed = string?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""

        // Images, unless they came with real text (a browser copying a page selection, for example).
        if trimmed.isEmpty, let png = Self.pngData(from: pb) {
            let hash = Self.hash(png)
            let file = "\(hash.prefix(16)).png"
            try? png.write(to: store.imagesFolder.appendingPathComponent(file))
            store.add(kind: .image, text: nil, rtf: nil, imageFile: file,
                      sourceBundleID: sourceID, sourceName: sourceName, hash: hash)
            return
        }

        guard let string, !trimmed.isEmpty else { return }
        store.add(kind: Self.classify(trimmed), text: string, rtf: pb.data(forType: .rtf), imageFile: nil,
                  sourceBundleID: sourceID, sourceName: sourceName, hash: Self.hash(Data(string.utf8)))
    }

    // MARK: Helpers

    private static func pngData(from pb: NSPasteboard) -> Data? {
        if let png = pb.data(forType: .png) { return png }
        guard let tiff = pb.data(forType: .tiff), let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    static func hash(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    static func classify(_ s: String) -> ClipKind {
        if isColor(s) { return .color }
        if !s.contains(where: \.isWhitespace), let url = URL(string: s),
           let scheme = url.scheme?.lowercased(), ["http", "https"].contains(scheme), url.host != nil {
            return .link
        }
        if looksLikeCode(s) { return .code }
        return .text
    }

    static func isColor(_ s: String) -> Bool {
        s.range(of: #"^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$"#, options: .regularExpression) != nil
            || s.range(of: #"^(rgb|rgba|hsl|hsla)\([^)]*\)$"#, options: [.regularExpression, .caseInsensitive]) != nil
    }

    /// A rough guess: several lines with the punctuation and indentation code tends to have.
    static func looksLikeCode(_ s: String) -> Bool {
        let lines = s.split(separator: "\n", omittingEmptySubsequences: false)
        let symbols = s.filter { "{}();=<>[]".contains($0) }.count
        let indented = lines.filter { $0.hasPrefix("  ") || $0.hasPrefix("\t") }.count
        let keywords = #"\b(func|function|const|let|var|import|return|class|def|if|for|=>|public|private|struct|SELECT|FROM)\b"#
        let hasKeyword = s.range(of: keywords, options: .regularExpression) != nil
        if lines.count == 1 { return hasKeyword && symbols >= 3 && s.count < 300 }
        return Double(symbols) / Double(max(s.count, 1)) > 0.03 && (indented > 0 || hasKeyword)
    }
}
